"""Google Drive → parse → encrypted vault. Read-only scope, PKCE desktop flow on loopback,
token and OAuth client JSON in the system keychain. Also accepts a local xlsx so the same
pipeline runs with no Google account at all.

    python sync.py                          # Drive, spreadsheet from config.toml
    python sync.py --source local:file.xlsx # a local export or synthetic data
    python sync.py --client-secret client_secret.json   # store the OAuth client once, in the keychain
    python sync.py --logout                 # forget the Drive token
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

import polars as pl

from kalecki.config import Config, load as load_config
from kalecki.parse import parse_workbook
from kalecki.store import KeyStore, Vault

SCOPES = ["https://www.googleapis.com/auth/drive.readonly"]
XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
GSHEET = "application/vnd.google-apps.spreadsheet"
TOKEN_ENTRY = "drive_token"
CLIENT_ENTRY = "oauth_client"
SYNC_LOG_SCHEMA = {"ts": pl.Datetime("us"), "source": pl.Utf8, "rows": pl.Int32, "checksum": pl.Utf8, "note": pl.Utf8}


# ----------------------------------------------------------------------------- auth

def store_oauth_client(ks: KeyStore, client_json: str) -> None:
    data = json.loads(client_json)
    if "installed" not in data:
        raise ValueError("expected a Desktop-app OAuth client JSON (top-level key 'installed')")
    ks.set(CLIENT_ENTRY, json.dumps(data))


def has_oauth_client(ks: KeyStore) -> bool:
    return bool(ks.get(CLIENT_ENTRY))


def has_token(ks: KeyStore) -> bool:
    return bool(ks.get(TOKEN_ENTRY))


def logout(ks: KeyStore) -> None:
    ks.delete(TOKEN_ENTRY)


def credentials(ks: KeyStore, interactive: bool = True):
    """Valid Drive credentials from the keychain; runs the browser consent on first use."""
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials

    raw = ks.get(TOKEN_ENTRY)
    creds = None
    if raw:
        creds = Credentials.from_authorized_user_info(json.loads(raw), SCOPES)
        if not creds.valid and creds.expired and creds.refresh_token:
            creds.refresh(Request())
            ks.set(TOKEN_ENTRY, creds.to_json())
    if creds and creds.valid and set(creds.scopes or []) >= set(SCOPES):
        return creds
    if not interactive:
        raise RuntimeError("no valid Drive token; sign in from the terminal or the sidebar first")
    client = ks.get(CLIENT_ENTRY)
    if not client:
        raise RuntimeError("no OAuth client stored; run: python sync.py --client-secret client_secret.json")
    from google_auth_oauthlib.flow import InstalledAppFlow

    flow = InstalledAppFlow.from_client_config(json.loads(client), SCOPES)
    # PKCE is generated by the flow itself; the redirect listener binds to loopback only.
    creds = flow.run_local_server(host="127.0.0.1", port=0, open_browser=True,
                                  authorization_prompt_message="Open this URL to sign in: {url}")
    ks.set(TOKEN_ENTRY, creds.to_json())
    return creds


# ----------------------------------------------------------------------------- drive

def export_sheet(creds, file_id: str) -> tuple[bytes, dict]:
    """The spreadsheet as xlsx bytes, plus its Drive metadata. Nothing is written to disk."""
    from googleapiclient.discovery import build

    svc = build("drive", "v3", credentials=creds, cache_discovery=False)
    meta = svc.files().get(fileId=file_id, fields="id,name,mimeType,modifiedTime,size", supportsAllDrives=True).execute()
    if meta.get("mimeType") == GSHEET:
        data = svc.files().export(fileId=file_id, mimeType=XLSX).execute()
    elif meta.get("mimeType") == XLSX:
        data = svc.files().get_media(fileId=file_id, supportsAllDrives=True).execute()
    else:
        raise RuntimeError(f"{meta.get('name')!r} is {meta.get('mimeType')}, not a Google Sheet or xlsx")
    return data, meta


# ----------------------------------------------------------------------------- pipeline

@dataclass
class SyncReport:
    source: str
    rows: int = 0
    units: int = 0
    trades: int = 0
    checksum: str = ""
    skipped: bool = False
    warnings: list[str] = field(default_factory=list)

    def __str__(self):
        if self.skipped:
            return f"{self.source}: unchanged (checksum {self.checksum[:12]}), nothing to do"
        w = f"; {len(self.warnings)} warning(s)" if self.warnings else ""
        return f"{self.source}: {self.rows} ledger rows, {self.units} units, {self.trades} trades{w}"


def ingest(data: bytes, source: str, cfg: Config, vault: Vault, force: bool = False) -> SyncReport:
    """Parse workbook bytes and merge the result into the vault."""
    checksum = hashlib.sha256(data).hexdigest()
    current = vault.load() if vault.exists() else {}
    log = current.get("sync_log", pl.DataFrame(schema=SYNC_LOG_SCHEMA))
    if not force and log.height and log.sort("ts").row(-1, named=True)["checksum"] == checksum and "rent_ledger" in current:
        return SyncReport(source=source, checksum=checksum, skipped=True)
    res = parse_workbook(data, cfg.ledger_tab, cfg.reference_tab, cfg.trades_tab, cfg.foreign_units)
    entry = pl.DataFrame([{
        "ts": dt.datetime.now(), "source": source, "rows": res.ledger.height, "checksum": checksum,
        "note": "; ".join(res.warnings)[:500],
    }], schema=SYNC_LOG_SCHEMA)
    vault.update(units=res.units, rent_ledger=res.ledger, trades=res.trades, sync_log=pl.concat([log, entry]))
    return SyncReport(source=source, rows=res.ledger.height, units=res.units.height, trades=res.trades.height,
                      checksum=checksum, warnings=res.warnings)


def sync(cfg: Config, ks: KeyStore | None = None, source: str | None = None, force: bool = False, interactive: bool = True) -> SyncReport:
    """source: None → Drive per config (or config.local_file if set); 'local:<path>' → that file."""
    ks = ks or KeyStore(cfg.keyring_service)
    vault = Vault(cfg.vault, ks)
    if source is None and cfg.local_file:
        source = f"local:{cfg.local_file}"
    if source and source.startswith("local:"):
        path = Path(source[6:]).expanduser()
        return ingest(path.read_bytes(), f"local:{path.name}", cfg, vault, force)
    creds = credentials(ks, interactive=interactive)
    data, meta = export_sheet(creds, cfg.spreadsheet_id)
    label = f"drive:{meta.get('name')} @ {meta.get('modifiedTime')}"
    return ingest(data, label, cfg, vault, force)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default="config.toml")
    ap.add_argument("--source", help="local:<path.xlsx> to bypass Drive")
    ap.add_argument("--client-secret", help="path to the Desktop OAuth client JSON; stored in the keychain, then delete the file")
    ap.add_argument("--force", action="store_true", help="re-parse even when the file is unchanged")
    ap.add_argument("--logout", action="store_true")
    a = ap.parse_args(argv)
    cfg = load_config(a.config)
    ks = KeyStore(cfg.keyring_service)
    if a.client_secret:
        store_oauth_client(ks, Path(a.client_secret).read_text())
        print("OAuth client stored in the keychain. You can delete the JSON file now.")
        return 0
    if a.logout:
        logout(ks)
        print("Drive token removed.")
        return 0
    try:
        print(sync(cfg, ks, a.source, a.force))
    except Exception as e:  # keep the traceback out of the owner's terminal; the message is enough
        print(f"sync failed: {type(e).__name__}: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
